### ISSUE TITLE
Home page issue

### ISSUE THREAD

**Issue by kubens** [matejlatin/Gutenberg#38] opened 2016-05-09 12:14 UTC
Hi!

I see some bug for home page. Check mov file:
https://www.dropbox.com/s/yoznhkske69fscw/gutenberg-bug.mov?dl=0

**Comment by Pustur** [comment] 2016-05-10 11:55
Duplicate of #30

**Comment by matejlatin** [comment] 2016-05-11 10:35
Yup, it's a duplicate. I'll close it.

**Closed by matejlatin** 2016-05-11 10:35 UTC
